services:
  web:
    build:
      context: .
      args:
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - UID=${UID}
        - GID=${GID}
    image: ${IMAGE_NAME}
    shm_size: '126gb'
    # vscodeならportsの設定はいらない
    # ports:
    #   - '8888:8888'
    volumes:
      - '../work:/work'
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: /work
    container_name: ${IMAGE_NAME}
    tty: true
    stdin_open: true
    environment:
      - COMET_API_KEY
    deploy:
      resources:
        reservations:
          devices:
          # 全てのGPUを使う設定
          # - capabilities: [gpu]
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
