version: '3'

services:
  web:
    build: .
    image: deep-learning
    ports:
      - '8888:8888'
    volumes:
      - '~/Desktop/work:/work'
      - '/Volumes/HDD/datasets:/datasets'
    working_dir: /work/pytorch
    container_name: deep-learning
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
