version: '3'

services:
  web:
    build: .
    image: pytorch_cpu
    ports:
      - '8888:8888'
    volumes:
      - '~/Desktop/work:/work'
      - '/Volumes/HDD/datasets:/datasets'
    working_dir: /work/pytorch_path_mnist
    container_name: pytorch_cpu
    tty: true
    stdin_open: true
